### ISSUE TITLE
Do system.groups().anonymous() work remotely?

### ISSUE THREAD

**Issue by alatdneg** [actor-framework/actor-framework#1315] opened 2022-01-07 11:36 UTC
I've got some code that passes the address of a group to a remote actor, which then joins the group, but the remote actor don't appear to get any of the messages sent to the group.

Is this expected to work ? 

The connection is opened by publishing the actor, I'm not using publish_local_groups, as I assumed that is used for discovery of remote named groups, not communication ? 

Or am I mistaken ? And I need to open two separate ports to enable direct and group messages.

cheers

**Comment by alatdneg** [comment] 2022-01-10 09:18
A bit more clarity..

Actor A creates a group,  G = system.groups().anonymous()
Remote actor B sends a request to A which then replies with G [=](get_group_atom) -> caf::group { return G; }
B then does join(G) which fails, (i checked the joined_groups() count).

I assumed the above would behave as another communication over the connection.

**Comment by Neverlord** [comment] 2022-01-10 19:48
I think this should work, but there are also some gotchas with groups. Are there in-between nodes or is it just two nodes? Do you happen to have a minimal reproducing example for this?

**Comment by alatdneg** [comment] 2022-01-11 07:50
There is a gateway node, that allows for the remote actor B to get the handle to A, which it then uses to get G. Does that count as in between nodes? i.e. A is not directly published.

**Comment by Neverlord** [comment] 2022-01-21 07:08
Is this example matching your use case? It triggers an assertion for me in CAF because doing anything with the anonymous group from remote causes the middleman to try send a message to an invalid peer. Didn't hunt it further down yet.

Groups probably get deprecated in the new release (aside from not providing a type-safe interface, groups have many pitfalls and limit design space), so I'm not sure if it's worth it to investigate further.

```cpp
#include <string>
#include <iostream>

#include "caf/actor_ostream.hpp"
#include "caf/actor_system.hpp"
#include "caf/caf_main.hpp"
#include "caf/event_based_actor.hpp"
#include "caf/io/middleman.hpp"

struct config : public caf::actor_system_config {
  config() {
    opt_group{custom_options_, "global"}
      .add<std::string>("mode,m", "mode of operation")
      .add<uint16_t>("port,p", "port for the gateway");
  }
};

// Sends to the group, once per second.
caf::behavior left(caf::event_based_actor* self, caf::actor group_provider) {
  self->request(group_provider, caf::infinite, caf::get_atom_v)
    .then([self](caf::group grp) {
      std::cout << "*** got the group, start sending\n";
      self->send(self, caf::tick_atom_v, grp);
    });
  return {
    [self, i = 0](caf::tick_atom, caf::group grp) mutable {
      using namespace std::literals;
      self->send(grp, ++i);
      self->delayed_send(self, 1s, caf::tick_atom_v, grp);
    },
  };
}

// Subscribes to the group.
caf::behavior right(caf::event_based_actor* self, caf::actor group_provider) {
  self->request(group_provider, caf::infinite, caf::get_atom_v)
    .then([self](caf::group grp) {
      std::cout << "*** got the group, join\n";
      self->join(grp);
    });
  return {
    [](int32_t x) { std::cout << "received: " << x << '\n'; },
  };
}

// Provides access to the group.
caf::behavior gateway(caf::event_based_actor* self) {
  auto grp = self->system().groups().anonymous();
  return {
    [grp](caf::get_atom) { return grp; },
  };
}

void caf_main(caf::actor_system& sys, const config&) {
  auto port = caf::get_or(sys.config(), "port", uint16_t{1234});
  auto mode = caf::get_or(sys.config(), "mode", std::string{});
  if (mode == "gateway") {
    auto hdl = sys.spawn(gateway);
    sys.middleman().publish(hdl, port);
  } else if (mode == "left") {
    if (auto hdl = sys.middleman().remote_actor("localhost", port)) {
      sys.spawn(left, *hdl);
    } else {
      std::cerr << "*** failed to connect to gateway\n";
    }
  } else if (mode == "right") {
    if (auto hdl = sys.middleman().remote_actor("localhost", port)) {
      sys.spawn(right, *hdl);
    } else {
      std::cerr << "*** failed to connect to gateway\n";
    }
  } else {
    std::cerr << "*** invalid mode\n";
  }
}

// creates a main function for us that calls our caf_main
CAF_MAIN(caf::io::middleman)
```

**Comment by alatdneg** [comment] 2022-01-21 09:04
Close the sender is local to the gateway. Only the receiver is remote.

Groups are going !?  We use those pretty heavily, is there going to be a equivalent replacement ?

**Comment by Neverlord** [comment] 2022-01-28 06:59
> is there going to be a equivalent replacement ?

Ideally, I'd like to make groups obsolete with the new flow API. That would kill two birds with one stone and also make pub/sub type safe.

**Comment by alatdneg** [comment] 2022-01-28 07:50
Cool, did you manage to reproduce the behaviour, I saw, I see it's tagged as a bug ? If this isn't going to be fixed do we have a rough idea as to when it's replacement will be available ?

For context the group events were going to be used to trigger callbacks in our python API, and also for some interactions between linked instances of the app. 

We don't need it immediately, but in a couple months it's going to be problematic.

**Comment by Neverlord** [comment] 2022-04-21 04:42
> If this isn't going to be fixed do we have a rough idea as to when it's replacement will be available ?

The ground work for the new flow API has been merged via #1325. Based on this, we're going to implement a new actor-to-actor streaming layer. I believe the new API can cover most of the use cases that groups currently have to offer but 1) in a type-safe manner, 2) with less opportunity to shoot yourself in the foot and 3) overall cleaner API. So I'm leaning towards deprecating groups altogether with 0.19. However, whether streams can actually be replacement for groups of course requires some real-world validation. @alatdneg how are you using groups in your code? In particular:

- Are you relying on anonymous groups only?
- Do you use the group registry (name lookups)?
- Do you use remote groups (`publish_local_groups`)?

Feel free to drop me a mail if you prefer more direct communication about that (or don't want to share too much details publicly). We could also do a quick video-chat/call if you prefer that over typing. 🙂

**Comment by alatdneg** [comment] 2022-04-21 06:55
Thanks for the reply, unfortunately in the meantime I had to expedite a fix
for this, so I replaced the groups using normal actors, possibly not as
efficient as using groups, but it basically worked.

We were using anonymous groups on the whole, (one was using the group
registry), I was investigating publishing them but that would have involved
opening a second connection to the system (actors were already connecting
remotely), which would have made life very awkward. I'd originally assumed
groups would just work over the original connection.

I'll have a look at the PR, as it might be relevant in other parts of our
code.

Hopefully in the very near future we'll have a micro-site for our project,
so you'll be able to see what we've been working on (using CAF as the
framework).

cheers

Al

**Comment by Neverlord** [comment] 2022-04-21 07:00
Ah, if you've transitioned away from groups in the meantime then I suppose there's not much holding back on deprecating them. This bug must exist since 0.18 and this ticket was the only time I heard about it from users. So I suppose groups aren't used widely anyway.

> I'll have a look at the PR, as it might be relevant in other parts of our code.

Unless you are eager to be super-early-adopter, I'd probably wait for some more examples or a CAFcademy article. 🙂

Closing as wontfix, then.

**Closed by Neverlord** 2022-04-21 07:00 UTC
Labels: bug

**Comment by alatdneg** [comment] 2022-04-21 07:04
Heh, yeah, I was just nosing around out of curiosity, I wouldn't assume
that groups aren't being used by other people just because they never
stumbled over my issue. I'd recommend announcing your intention in a way
that people will be aware of.

**Comment by Neverlord** [comment] 2022-04-21 07:11
> I'd recommend announcing your intention in a way that people will be aware of.

Yes, there are going to be more announcements regarding changes in 0.19. This is going to be quite a big cleanup and shift in focus for CAF. And hopefully the last "Version 0" release.
