### ISSUE TITLE
No released version of CAF builds on clang/libc++ 4

### ISSUE THREAD

**Issue by copumpkin** [actor-framework/actor-framework#545] opened 2017-03-29 00:33 UTC
I'm running this under Nix, so the environment is a little bit non-standard, but I don't _think_ that should affect this issue. Here's a log of what happens when I run `make` (after configuring etc.):

```
$ make 
[  0%] Built target libcaf_io
[  0%] Built target libcaf_core
Scanning dependencies of target libcaf_core_shared
[  1%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/abstract_actor.cpp.o
[  1%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/abstract_channel.cpp.o
[  2%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/abstract_composable_behavior.cpp.o
[  2%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/abstract_group.cpp.o
[  3%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/abstract_coordinator.cpp.o
[  3%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/actor.cpp.o
[  3%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/actor_addr.cpp.o
[  4%] Building CXX object libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/actor_config.cpp.o
In file included from /private/var/folders/vv/17b_hycx691699h20v458fnh0000gn/T/nix-build-actor-framework-0.15.3.drv-0/actor-framework-0.15.3-src/libcaf_core/src/actor_config.cpp:20:
In file included from /private/var/folders/vv/17b_hycx691699h20v458fnh0000gn/T/nix-build-actor-framework-0.15.3.drv-0/actor-framework-0.15.3-src/libcaf_core/caf/actor_config.hpp:23:
In file included from /nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/string:470:
In file included from /nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/string_view:171:
In file included from /nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/__string:56:
In file included from /nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/algorithm:637:
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/type_traits:4301:23: error: calling 'operator()' with incomplete return type 'caf::behavior'
_LIBCPP_INVOKE_RETURN(_VSTD::forward<_Fp>(__f)(_VSTD::forward<_Args>(__args)...))
~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/__config:390:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/type_traits:4198:23: note: expanded from macro '_LIBCPP_INVOKE_RETURN'
    noexcept(noexcept(__VA_ARGS__)) -> decltype(__VA_ARGS__) \
                      ^~~~~~~~~~~
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/type_traits:4318:9: note: in instantiation of exception specification for '__invoke<std::__1::function<caf::behavior (caf::local_actor *)> &, caf::local_actor *>' requested here
        _VSTD::__invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...));
        ^
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/__config:390:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/functional:1591:33: note: in instantiation of template class 'std::__1::__invokable_r<void, std::__1::function<caf::behavior (caf::local_actor *)> &, caf::local_actor *>' requested
      here
                                __invokable<_Fp&, _ArgTypes...>::value>
                                ^
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/functional:1616:9: note: in instantiation of default argument for '__callable<std::__1::function<caf::behavior (caf::local_actor *)> >' required here
        __callable<_Fp>::value && !is_same<_Fp, function>::value
        ^~~~~~~~~~~~~~~
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/functional:1618:5: note: in instantiation of default argument for 'function<std::__1::function<caf::behavior (caf::local_actor *)> >' required here
    function(_Fp);
    ^~~~~~~~~~~~~
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/functional:1578:28: note: while substituting deduced template arguments into function template 'function'
      [with _Fp = std::__1::function<caf::behavior (caf::local_actor *)>, $1 = (no value)]
class _LIBCPP_TEMPLATE_VIS function<_Rp(_ArgTypes...)>
                           ^
/nix/store/rxlqwjiwwp5v7h1wp39gxlkb9j2cvchd-libc++-4.0.0/include/c++/v1/functional:1670:9: note: 'operator()' declared here
    _Rp operator()(_ArgTypes...) const;
        ^
/private/var/folders/vv/17b_hycx691699h20v458fnh0000gn/T/nix-build-actor-framework-0.15.3.drv-0/actor-framework-0.15.3-src/libcaf_core/caf/fwd.hpp:62:7: note: forward declaration of 'caf::behavior'
class behavior;
      ^
1 error generated.
make[2]: *** [libcaf_core/CMakeFiles/libcaf_core_shared.dir/build.make:231: libcaf_core/CMakeFiles/libcaf_core_shared.dir/src/actor_config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:222: libcaf_core/CMakeFiles/libcaf_core_shared.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

There seems to be a ton of standard C++ files in the error message which is making it rather hard for me to follow what in particular in CAF is triggering it. 

As far as I've been able to tell, [this line](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/actor_config.hpp#L38) (`std::function<behavior (local_actor*)> init_fun;`) is running afoul of some static check due to the forward declaration of `behavior` in [fwd.hpp](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/fwd.hpp#L62). I haven't been able to decipher what's going on beyond that.

**Comment by Hamdor** [comment] 2017-03-29 06:24
Which version of clang do you use?

**Comment by copumpkin** [comment] 2017-03-29 08:48
Just 4.0

**Comment by Hamdor** [comment] 2017-03-29 09:16
I was not able to reproduce this with Clang 4.0 on OSX. Could you add `#include "caf/behavior.hpp"` in `actor_config.hpp` and report back if this fixes this compile issue?

**Comment by copumpkin** [comment] 2017-03-29 09:17
Will do when I get back to my computer later today! Just to double check,
you're using libc++ 4 with clang 4?

**Comment by Hamdor** [comment] 2017-03-29 09:36
This bug is already fixed in develop with [this](https://github.com/actor-framework/actor-framework/commit/c5a3ee26a6e76b28dd4226f35230b280f291386d) commit.

**Comment by copumpkin** [comment] 2017-03-29 09:37
Oh, amazing, thanks! I should've tried a build from the branch before
filing. I'll close!

**Comment by Hamdor** [comment] 2017-03-29 09:40
We should keep this ticket open until next release

**Comment by copumpkin** [comment] 2017-03-29 09:41
Sounds good!

**Comment by sourcedelica** [comment] 2017-09-23 02:27
Same issue with Apple Clang 9.0, which Apple just pushed out via App Store automated updates to Xcode.

**Comment by grahamreeds** [comment] 2017-09-23 05:33
Any clue as to why they don't build?

GR

**Comment by sourcedelica** [comment] 2017-09-23 05:39
There is a commit referenced by Hamdor above that fixes the problem.  It adds a `#include` to `actor_config.hpp`.   Not sure why it wasn't a problem for the other compilers.

**Closed** 2017-09-29 09:44 UTC
Labels: bug, fixed in develop
