### ISSUE TITLE
missing close-frame when shutting down websocket server

### ISSUE THREAD

**Issue by allspark** [actor-framework/actor-framework#1938] opened 2024-08-12 16:18 UTC
When sending a `kill SIGTERM` to the [websocket example](https://github.com/interance/warehouse-backend-example/tree/main) currently open websocket connections do not receive a close-frame.

Changing the [consume of frames](https://github.com/interance/warehouse-backend-example/blob/main/warehouse-backend-example/main.cpp#L80) to 

```
auto disposable_push = std::make_shared<caf::disposable>();
pull.observe_on(self)
            .do_finally([] { applog::info("WebSocket client disconnected"); })
            .for_each([disposable_push](const frame& in) mutable {
              applog::info("In: {}", in.as_text());
              disposable_push->dispose();
            });
```

and [line 87](https://github.com/interance/warehouse-backend-example/blob/main/warehouse-backend-example/main.cpp#L87) to
```
*disposable_push = events.observe_on(self)
```
then the connection receives a close-frame when sending some data. This seem to work only with the `producer`, 
doing the same with the consumer doesn't generate a close-frame

**Comment by Neverlord** [comment] 2024-08-14 06:50
Thanks for reporting! Doing the manual dispose shouldn't be necessary, but we'll have to dig into it to see why it makes a difference.

**Comment by riemass** [comment] 2024-11-11 15:08
I've tested this locally and the close frame didn't show up as in the description. Also, I've been trying to reproduce the fix and I don't see any difference with and without the suggested code changes. Might be that I've misinterpreted something. 

I've been using `websocat ws://localhost:8080/events -v` , with the -v switch printing `ping`/`pong` and `close` frames. In cases where the server shuts down the client sees a tcp connection close, and the status gets set to 1006 ([which is the norm per rfc6455](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.5) if no close frame is present).

Just as a note, I've tested the `ws`, `wscat` and `websocat` CLI tools in server mode, and none of them ship a websocket closing frame when terminated with SIGINT and SIGTERM. The connection closes by shutting down the socket, and the client sees the code 1005 or 1006, similar to how we handle it. As I've understood the RFC, the server can abort the connection [without a close frame](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.1).

I'll have to check up our networking stack to see what happens when we shut down the net module, and if the close frame would be too hard to implement. As far as I see it's not just a forgotten dispose.

**Comment by Neverlord** [comment] 2024-11-15 10:43
A graceful connection close should send a close frames. IIRC, we do that in the code. Could it be that we just don't give the socker manager an opportunity to write the close frame because we are shutting down the network manager too quickly? After receiving sigterm, we dispose the server and send an exit message to the DB actor right before leaving main. When adding a sleep there (before leaving `caf_main`), will it send the close frame? Or aren't we actually never sending it in the first place?

I think closing the connection without sending a close frame should only be done in exceptional cases like protocol violations (e.g. receiving malformed WebSocket frames) or if the remote side is stalling.

**Closed** 2024-12-01 12:56 UTC
Labels: bug
