### ISSUE TITLE
Persistant linking error

### ISSUE THREAD

**Issue by jaked122** [actor-framework/actor-framework#277] opened 2015-04-30 20:41 UTC
```
undefined reference to "caf::io::publish_impl(caf::intrusive_ptr<caf::abstract_actor>, unsigned short, char const*, bool)" 
```

This is persistent when compiling with the caf::io library and using publish on a class based actor, or functor based actor. 

It also, does not work with remote_actor.
```
$>nm libcaf_io.so |c++filt|grep "caf::io::publish_impl"

000000000007e6d0 T caf::io::publish_impl(caf::intrusive_ptr<caf::abstract_actor>, unsigned short, char const*, bool)
```

It's in there, it's just not getting called correctly, it seems

**Comment by mavam** [comment] 2015-05-01 03:18
Can you please provide a minimal reproducible test case and describe your build harness?

**Comment by jaked122** [comment] 2015-05-01 17:33
Sure.
```c++
#include <caf/all.hpp>
#include <caf/io/all.hpp>
using namespace caf;
using namespace caf::io;
behavior failuremode(event_based_actor* self){
   return{
       [=](int n){
          return n+1;
       }
   };
}

int main(){
   auto i=spawn(failuremode);
   publish(i,0);
   await_all_actors_done();
   return 0;
}
```

Okay, the makefile I use for this is
```makefile
CC = g++
CCOPT = -std=c++11 -finstrument-functions -g 
LINKOPT = -L\usr\local\lib\ -lcaf_io -lcaf_core

executable: client server

client:main.cpp utility.o
	$(CC) $(CCOPT) -o client main.cpp  utility.cpp $(LINKOPT)

server:server.cpp utility.o
	$(CC) $(CCOPT) -o server server.cpp utility.o $(LINKOPT)

utility.o: utility.cpp utility.h
	$(CC) $(CCOPT) -c utility.cpp
```

If I swap the order of the libraries, it gives an error like `error adding symbols: DSO missing from command line`, which seems to be consistent with the kind of library bug that is caused by dependencies loaded in the wrong order.

**Comment by Hamdor** [comment] 2015-05-03 20:50
Have you tried to replace the backslash with a slash in `LINKOPT` ?
==> `LINKOPT = -L/usr/local/lib/ -lcaf_core -lcaf_io`

**Comment by Neverlord** [comment] 2015-05-05 15:00
I cannot reproduce this issue on Fedora:

```
$ cat Makefile 
CC = g++
CCOPT = -std=c++11 -finstrument-functions -g -I./libcaf_io -I./libcaf_core
LINKOPT = -L./build/lib/ -lcaf_io -lcaf_core

all:
	$(CC) $(CCOPT) -o test test.cpp $(LINKOPT)

$ make
g++ -std=c++11 -finstrument-functions -g -I./libcaf_io -I./libcaf_core -o test test.cpp -L./build/lib/ -lcaf_io -lcaf_core

$ ldd test
	linux-vdso.so.1 =>  (0x00007fff571fe000)
	libcaf_io.so.0.13.2 => /var/lib/jenkins/data/workspace/CAF/develop branch gcc/label_exp/Linux && gcc4.7/build/lib/libcaf_io.so.0.13.2 (0x00007fab5717c000)
	libcaf_core.so.0.13.2 => /var/lib/jenkins/data/workspace/CAF/develop branch gcc/label_exp/Linux && gcc4.7/build/lib/libcaf_core.so.0.13.2 (0x00007fab56c02000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00000038c8c00000)
	libm.so.6 => /lib64/libm.so.6 (0x00000038c6400000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00000038c6800000)
	libc.so.6 => /lib64/libc.so.6 (0x00000038c4800000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00000038c5000000)
	/lib64/ld-linux-x86-64.so.2 (0x00000038c4400000)

$ g++ --version
g++ (GCC) 4.7.2 20121109 (Red Hat 4.7.2-8)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cat /etc/issue
Fedora release 18 (Spherical Cow)
Kernel \r on an \m (\l)
```

**Comment by mavam** [comment] 2015-05-05 19:17
I'm closing this one because of invalid path in `LINKOPT` that prevents the linking to take place.

**Closed by mavam** 2015-05-05 19:17 UTC
Labels: invalid
