### ISSUE TITLE
Doxygen: much of the documentation has seemingly vanished

### ISSUE THREAD

**Issue by ethindp** [actor-framework/actor-framework#1916] opened 2024-07-16 00:40 UTC
If you visit the doxygen documentation for version 1.0.0, you'll find that the namespace list only documents the `std` namespace, and that the class list doesn't have any of the documentation of the namespaces themselves anymore like was in 0.19 or most of the classes. This makes it rather tricky to actually navigate the documentation.

This is easy to reproduce: just build the documentation locally. The workaround is to set `extract_all` in the doxyfile to YES, but this has the unintended side-effect of adding documentation for internal stuff that probably shouldn't be in the doxygen to begin with.

**Comment by Neverlord** [comment] 2024-07-16 11:45
Thank you for bringing this to our attention! We'll look into it.

**Comment by shariarriday** [comment] 2024-07-17 18:25
I have found out that the issue is reproduced only for latest version of doxygen. As a temporary fix, [1.10.0](https://github.com/doxygen/doxygen/releases) version can be used to generate the documentation. I am also working on updating the codebase to ensure it is compliant with new versions of doxygen.

**Comment by ethindp** [comment] 2024-07-17 18:50
I'm curious what makes Doxygen 1.11 mess up with this, it doesn't look like anything breaking is in 1.11 according to the changelog...

**Comment by shariarriday** [comment] 2024-07-17 19:35
I am not sure what is breaking in 1.11. But, it would be great if you could confirm if the issue is fixed with 1.10. As of now I have found nothing in the changelog or doc that may cause the issue. But, I will share my findings here.

**Closed** 2024-07-26 06:59 UTC
Labels: documentation

**Comment by Neverlord** [comment] 2024-07-26 07:05
I've re-build and re-uploaded the documentation after the patch. Looks like the missing class documentation is back online.
