### ISSUE TITLE
does "send" always execute successfully

### ISSUE THREAD

**Issue by XMatrixXiang** [actor-framework/actor-framework#1596] opened 2023-10-10 08:06 UTC
I found a problem:

spawn a event_based_actor A;
spawn a blocking_actor B；
A sends a message to B via “send”;
Execute the above logic many times, and find that sometimes, B cannot receive the message from A, does "send" always execute successfully?

**Comment by riemass** [comment] 2023-10-10 11:56
Hi. Could you provide us with the code, at least a minimal example, so I can examine what's going on? I assume you did receive the message in B by calling `receive` or `receive_while`.

**Comment by XMatrixXiang** [comment] 2023-10-11 01:00
> Hi. Could you provide us with the code, at least a minimal example, so I can examine what's going on? I assume you did receive the message in B by calling `receive` or `receive_while`.

The project is a bit complicated, I need to take a moment to simplify a demo, in "caf::blocking_actor" I use "do_receive until"

**Comment by Neverlord** [comment] 2023-11-23 09:57
> does "send" always execute successfully?

Yes, it's basically just appending to the end of a queue. Closing the ticket only because it hasn't been updated in a while. Feel free to re-open if you have a reproducer that would allow us identifying an issue.

**Closed by Neverlord** 2023-11-23 09:57 UTC
Labels: question
