### ISSUE TITLE
inline_all_enqueues not working as expected

### ISSUE THREAD

**Issue by xiewei20082008** [actor-framework/actor-framework#1016] opened 2020-01-17 17:12 UTC
Unit tests fail to work on the code where scoped_actor is involved. I tried to add `sched.inline_all_enqueues()` before, but it still didn't work. Is there any way to make the scheduler run? The sample code is as follows. Thank you a lot.

```cpp
behavior inc_impl(event_based_actor *self) {
  return {
    [=](int x) {
      return x+1;
    }
  };
}

behavior a_impl(event_based_actor *self, actor &inc_actor) {
  return {
    [=](int x) {
      if (x==1) {
        scoped_actor sc{self->system()};
        cout << "before request" << endl;                            
        sc->request(inc_actor, caf::infinite, 1).receive(    // get stuck here.
          [=](int x) {
            cout << x << endl;
          },
          [=](caf::error &e) {}
        );
        cout << "after request" << endl;
      }
      else if(x==2) {
        cout << "before request" << endl;
        make_function_view(inc_actor)(1);    // get stuck here.
        cout << "after request" << endl;
      }
    }
  };
}

struct test_fixture : test_coordinator_fixture<> {
    test_fixture() {
    }
};

CAF_TEST_FIXTURE_SCOPE(test1, test_fixture)

CAF_TEST(blocked actor) {
  sched.inline_all_enqueues();
  auto inc_actor = sys.spawn(inc_impl);
  auto a_actor = sys.spawn(a_impl, inc_actor);
  self->send(a_actor, 1);
  // self->send(a_actor, 2);
  run();
}

CAF_TEST_FIXTURE_SCOPE_END()
```

**Comment by Neverlord** [comment] 2020-01-18 06:47
Thanks for providing the minimal example. I've reproduced the issue and I've implemented [a patch](https://github.com/actor-framework/actor-framework/pull/1017). If the PR gets merged, I'll also provide the patch in the branch `topic/0.17.4` (using the `master` branch is currently not a good idea, since it contains some breaking changes and more are coming for the upcoming 0.18 release).

However, please note that using a scoped actor *inside* an event-based actor is *not* safe. Event-based actors are scheduled *cooperatively*, this means they are supposed to "play nice" with each other.

The scheduler waits for the actor to return from its message handler before it can run other actors. Blocking a scheduler thread can degrade performance and cause starvation or even deadlocks.

Please consider using `self->request().then/await` instead or switch to using blocking actors instead if you really need a blocking `receive`.

**Closed** 2020-01-18 12:34 UTC
Labels: bug

**Comment by xiewei20082008** [comment] 2020-01-21 12:35
Also thank you for the advise on using event-based actors. I refactored my code - it was of great help to me.

**Comment by Neverlord** [comment] 2020-01-21 13:13
My pleasure. :)
