### ISSUE TITLE
Minimal possible example blocks forever in caf::actor_system destructor

### ISSUE THREAD

**Issue by ChristofferGreen** [actor-framework/actor-framework#951] opened 2019-10-27 04:28 UTC
The smallest possible code example I can do:

`#include <caf/all.hpp>

int main(int argc, char *argv[]) {
  caf::actor_system_config cfg;
  caf::actor_system system(cfg);

  return 0;
}
`

Blocks forever, never exists, in the destructor of system. I am using (mingw/msys2) GCC 9.2.0  on windows 10. Using CAF 0.17.2.

**Comment by ChristofferGreen** [comment] 2019-10-27 06:11
From printf debugging it appears to be these lines at the end of the destructor that hangs forever:

"  while (!logger_dtor_done_)
    logger_dtor_cv_.wait(guard);
"

**Comment by ChristofferGreen** [comment] 2019-10-27 06:23
It looks like the logger constructor gets called but the destructor (via reset on it's pointer) does not ever get called.

**Comment by ChristofferGreen** [comment] 2019-10-27 10:50
Here is the ref_counted::deref() function in ref_counted.cpp

"
void ref_counted::deref() const noexcept {
  if (unique()) {
    request_deletion(false);
    return;
  }
  if (rc_.fetch_sub(1, std::memory_order_acq_rel) == 1) {
    request_deletion(true);
  }
}
"

Neither if statement is entered. I don't know the code very well but I suspect this causes the logger to not be deleted.

**Comment by ChristofferGreen** [comment] 2019-10-27 15:59
Putting: 
    "std::cout << "handle count: " << logger_.get()->get_reference_count() << std::endl;" 
Before the "logger_.reset();" line in actor_system::~actor_system() results in: "handle count: 27"

Figuring out what is going on here is a bit above my head.

**Comment by Neverlord** [comment] 2019-10-27 19:27
Thank you for narrowing this down already! We'll try to reproduce this next week and see who's holding onto the references. :)

**Comment by Neverlord** [comment] 2019-10-29 09:32
@ChristofferGreen I had no luck reproducing this on my end so far.

> I am using (mingw/msys2) GCC 9.2.0 on windows 10. Using CAF 0.17.2.

Please note that we do *not* support MinGW officially. We're open to patches from the community for MinGW, but we don't maintain or test the MinGW code paths. Maintainers for that are welcome, btw. 😉

However, we *do* support Visual Studio for regular Windows builds. To make sure we're not dealing with some MingGW issue here: can you reproduce this behavior when using MSVC or when running on Linux?

**Comment by ChristofferGreen** [comment] 2019-10-30 06:26
Thank you for looking into it. It’s some kind of weird memory bug so not too surprising that it’s hard to replicate. I currently suspect that it is due to caf getting compiled in c++11 mode while the exe is compiled in c++17 model. You would not think that would be a big deal but I suspect mingw doesn’t like it. I’ll poke around a little around that when I get back home on Friday.

**Comment by ChristofferGreen** [comment] 2019-11-05 05:06
I have now had a chance to see if compiling caf and the .exe at the same c++ language level made a difference. Unfortunately it did not. I can verify that caf works fine using microsoft visual studio community 2019. 

I made the files I use to see the bug public here: https://github.com/ChristofferGreen/caf_example

At this point I am not sure what to do. Closing the bug as can not reproduce would be fine I suppose. Weird memory bugs are hard to track down after all. Maybe later I could spend some time fixing it, or just switch to visual studio, not sure yet.

Also, I found a strange quirk, when compiling for visual studio within both visual studio code (with cmake plugin) and visual studio community 2019 (by simply opening the example github folder I gave above and hitting build all), the visual studio compiler keeps complaining about this: "cl : Command line warning D9002 : ignoring unknown option '-std=c++11'"

It appears that the caf CMake file hard codes the c++ version. The code still ends up compiling however so it's a minor issue. And this issue does not happen if you tell cmake to generate visual studio project files and compiling from them.

**Comment by Neverlord** [comment] 2019-11-06 08:55
> It appears that the caf CMake file hard codes the c++ version.

Yes, our CMake scaffold needs some cleanup. We're probably going to do that as part of migrating to CMake 3.0 in the next couple of weeks.

> I can verify that caf works fine using microsoft visual studio community 2019.

Ok, thank you for double-checking! I'm closing this, since it seems to be a MinGW issue and we don't officially support that platform. Should you ever end up tracking this down, we're of course accepting fixes for MinGW.

**Closed by Neverlord** 2019-11-06 08:55 UTC
Labels: bug
